# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 650f172f26d38c80c4873763d6579d2904c6faafc02f7dff8edb5f058d0a26f7c6dff32967a60f2f8bcc4ef3a2ecde2ede91ea46cfef1c03a92bb67d9f658346

test:
  secret_key_base: a965ddcc3ed5224b753ade92b247c82e67518a917fa2f7f63180b0e0b535768646abab39d9b8e3b8887148f361575e49f4421931b2b32d350f43d4ff06710fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
